<?php

    namespace common\components;

    use common\models\LogModel;
    use common\models\ProductModel;
    use Yii;
    use yii\base\Component;
    use yii\base\Event;
    use yii\base\Exception;
    use yii\db\ActiveRecord;
    use yii\db\BaseActiveRecord;

    class LogComponent extends Component{
        public $a;

        public function init(){
            parent::init(); // TODO: Change the autogenerated stub
            Event::on(ActiveRecord::className(), ActiveRecord::EVENT_AFTER_UPDATE, [self::className(), 'test']);
        }

        public function events(){
            return [
                ActiveRecord::EVENT_AFTER_INSERT => 'logInsert',
                ActiveRecord::EVENT_AFTER_UPDATE => 'logUpdate',
                ActiveRecord::EVENT_AFTER_DELETE => 'logDelete',
            ];
        }

        public static function test(){
            throw new Exception('event ok!');
        }

        public function logInsert($event){
            $log = new LogModel([
                                    'action'      => 'insert',
                                    'action_data' => json_encode($event),
                                    'initializer' => 'admin',
                                    'user_id'     => Yii::$app->user->id
                                ]);
            $log->save();
        }

        public function logUpdate($event){
            $log = new LogModel([
                                    'action'      => 'update',
                                    'action_data' => json_encode($event),
                                    'initializer' => 'admin',
                                    'user_id'     => Yii::$app->user->id
                                ]);
            $log->save();
        }

        public function logDelete($event){
            $log = new LogModel([
                                    'action'      => 'delete',
                                    'action_data' => json_encode($event),
                                    'initializer' => 'admin',
                                    'user_id'     => Yii::$app->user->id
                                ]);
            $log->save();
        }
    }